name: build

on:
  workflow_call:

env:
  GO_VERSION: "1.22"
  DESTDIR: "./bin"

jobs:
  binaries:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    
    - name: Linux
      run: |
        make build-linux GO_BINDIR=${{ env.DESTDIR }}
      
    - name: MacOS
      run: |
        make build-macos GO_BINDIR=${{ env.DESTDIR }}
    
    - name: Windows
      run: |
        make build-windows GO_BINDIR=${{ env.DESTDIR }}
    
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: assets
        path: "${{ env.DESTDIR }}"
        if-no-files-found: error