name: ci-cd
on:
  push:
    branches:
      - "master"
      - "v[0-9]*"
      - "feature/*"
      - "fix/*"

    tags:
      - "v*"

  pull_request:
    branches:
      - "master"

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  test:
    needs: prepare
    uses: ./.github/workflows/test.yml

  build:
    needs: [prepare, test]
    uses: ./.github/workflows/build.yml
    secrets: inherit

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    uses: ./.github/workflows/release.yml
    secrets: inherit
