name: ci-cd
on:
  push:
    branches:
      - 'master'
      - 'v[0-9]*'
      - 'feature/*'
      - 'fix/*'

    tags:
      - 'v*'

  pull_request:
    branches:
      - 'master'

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml

  delete-package-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: deleteimg
        uses: actions/delete-package-versions@v2
        with:
          token: ${{ secrets.UNBKD_CICD_TOKEN }}
          package-version-ids: "*"
          package-name: "elcli"
          owner: "unbrikd"
          repo: "elcli"

  # build:
  #   needs: prepare
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit

  # release:
  #   needs: build
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   uses: ./.github/workflows/release.yml
  #   secrets: inherit