name: ci-cd
on:
  push:
    branches:
      - 'master'
      - 'v[0-9]*'
      - 'feature/*'
      - 'fix/*'

    tags:
      - 'v*'

  pull_request:
    branches:
      - 'master'

jobs:
  prepare:
    uses: ./.github/workflows/prepare.yml
  
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set release version
        run: |
          version=$(make print-version)
          echo "APPLICATION_VERSION=${version}" >> $GITHUB_ENV


      - name: Log in to GitHub Docker Registry
        run: docker login ghcr.io -u unbrikd --password ${{ secrets.GHCR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push multi-architecture Docker image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            --push \
            --tag ghcr.io/unbrikd/elcli:latest \
            --tag ghcr.io/unbrikd/elcli:${{ env.APPLICATION_VERSION }} \
            -f ./docker/Dockerfile .

  # build:
  #   needs: prepare
  #   uses: ./.github/workflows/build.yml
  #   secrets: inherit

  # release:
  #   needs: build
  #   if: startsWith(github.ref, 'refs/tags/v')
  #   uses: ./.github/workflows/release.yml
  #   secrets: inherit