name: release

on:
  workflow_call:

jobs:
  verify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v2

    - name: Verifying the application version
      run: |
        echo "Version is v$(make print-version)"