name: release

on:
  workflow_call:

jobs:
  unit-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Execute unit tests
        run: |
          make unit-tests
